### ISSUE TITLE
师兄您好，我也是来自北邮的学生，想学习一下您的代码

### ISSUE THREAD

**Issue by liwenwei123** [ShuaiBai623/AI-City-Anomaly-Detection#7]
第一步生成oriimageg和process image之后，发现无法直接运行detect_anomaly测试，还缺少了生成detection result部分的代码，请问您方便提供一下生成detection result部分的代码吗，感激不尽！

**Comment by sgq123** [comment]
> 第一步生成oriimageg和process image之后，发现无法直接运行detect_anomaly测试，还缺少了生成detection result部分的代码，请问您方便提供一下生成detection result部分的代码吗，感激不尽！

同学你好，你的问题解决没有，我最近也在学习这个方向，可以交流下吗

**Comment by liwenwei123** [comment]
你好，detection部分我直接用的mmdetection的代码，在https://github.com/ShuaiBai623/AI-City-Anomaly-Detection/tree/master/src/detection/README.md里有说明后续的操作步骤




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"sgq123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月26日(星期天) 晚上6:10
收件人:&nbsp;"ShuaiBai623/AI-City-Anomaly-Detection"<AI-City-Anomaly-Detection@noreply.github.com&gt;;
抄送:&nbsp;"李文蔚"<804363096@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [ShuaiBai623/AI-City-Anomaly-Detection] 师兄您好，我也是来自北邮的学生，想学习一下您的代码 (#7)





  
第一步生成oriimageg和process image之后，发现无法直接运行detect_anomaly测试，还缺少了生成detection result部分的代码，请问您方便提供一下生成detection result部分的代码吗，感激不尽！
  
同学你好，你的问题解决没有，我最近也在学习这个方向，可以交流下吗

**Comment by sgq123** [comment]
非常感谢！同学我给你发送qq了，可以接受下吗哈哈
